# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: TSAR

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm install'
    workingDirectory: './src/store-front/'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'dependency-check.sh --project store-front --scan ./src/store-front -f HTML --nvdApiKey aea87987-488a-4f7d-a151-41c3b2c1f92d'

- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/tsar/myagent/_work/2/s/./'
    Contents: '**/.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'owasp'
    publishLocation: 'Container'